# Default profile configuration (for local development with IDE)
server:
  port: 8081

spring:
  application:
    name: register-service

  datasource:
    url: jdbc:postgresql://localhost:5433/hypersend
    username: ${POSTGRES_USER:hypersend_user}
    password: ${POSTGRES_PASSWORD:hypersend_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariPool-RegisterUser
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: true

# Application configuration
app:
  # Gateway authentication secret for internal communications
  gateway:
    secret: ${GATEWAY_SECRET:shared_secret_key}

  # User validation settings
  validation:
    password:
      min-length: 8
      max-length: 255
    username:
      min-length: 3
      max-length: 50
    email:
      max-length: 255

# Logging configuration
logging:
  level:
    com.thm_modul.register_user: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

---
# Docker profile configuration (when running inside containers)
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://hps_postgres:5432/hypersend}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariPool-RegisterUser-Docker
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: false

# Application configuration (same for all profiles)
app:
  gateway:
    secret: ${GATEWAY_SECRET:shared_secret_key}
  validation:
    password:
      min-length: 8
      max-length: 255
    username:
      min-length: 3
      max-length: 50
    email:
      max-length: 255

# Logging configuration for containerized environment
logging:
  level:
    com.thm_modul.register_user: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints (same for all profiles)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always