# Default profile configuration (for local development with IDE)
server:
  port: 8081

spring:
  application:
    name: register-service

  datasource:
    # ✅ CORRECTED: Use 'hypersend' database name, not 'users'
    url: jdbc:postgresql://localhost:5433/hypersend
    username: ${POSTGRES_USER:hypersend_user}
    password: ${POSTGRES_PASSWORD:hypersend_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariPool-RegisterService
      minimum-idle: 2

  jpa:
    hibernate:
      # ✅ CORRECT: validate to use SQL initialization scripts
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: true

# Logging configuration
logging:
  level:
    com.thm_modul.register_user: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Docker profile configuration (when running inside containers)
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    # ✅ CORRECT: Use environment variables set by docker-compose
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://hps_postgres:5432/hypersend}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariPool-RegisterService-Docker
      minimum-idle: 2

  jpa:
    hibernate:
      # ✅ CORRECT: validate because DB is already initialized by SQL scripts
      ddl-auto: validate
    show-sql: false  # Less verbose in containers
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: false

# Logging configuration for containerized environment
logging:
  level:
    com.thm_modul.register_user: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"