server:
  port: 8082

spring:
  application:
    name: users

  datasource:
    url: jdbc:postgresql://localhost:5433/users  # Port mappé sur l'hôte
    username: ${POSTGRES_USER:user_1}
    password: ${POSTGRES_PASSWORD:pass_1}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariPool-Users
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      indent_output: true

