services:
  hps_postgres:
    container_name: hps_postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/hps_postgres
    volumes:
      - hps_postgres_data:/data/hps_postgres
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - hps_postgres_network
    restart: unless-stopped

  hps_pgadmin:
    container_name: hps_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - hps_pgadmin_data:/var/lib/pgadmin
    ports:
      - "5051:80"
    networks:
      - hps_postgres_network
    restart: unless-stopped

networks:
  hps_postgres_network:
    driver: bridge

volumes:
  hps_postgres_data:  # Neues Volume für PostgreSQL
  hps_pgadmin_data:    # Neues Volume für pgAdmin