server:
  port: 8083

spring:
  application:
    name: login-service
  datasource:
    url: jdbc:postgresql://localhost:5433/users  # Port mappé sur l'hôte
    username: ${POSTGRES_USER:user_1}
    password: ${POSTGRES_PASSWORD:pass_1}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariPool-Users
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuration JWT
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 heures en millisecondes
  refresh-expiration: 604800000 # 7 jours en millisecondes

logging:
  level:
    com.thm_modul.login_service: DEBUG
    org.springframework.security: DEBUG